openapi: 3.0.0
paths:
  /api:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
  /api/guardians:
    get:
      operationId: GuardianController_getAllGuardians
      parameters: []
      responses:
        "200":
          description: ""
  "/api/guardians/{id}":
    get:
      operationId: GuardianController_getGuardianById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
info:
  title: guardian-service
  description: Resource Server
  version: 0.1.0.alpha
  contact: {}
tags: []
servers: []
components:
  schemas: {}
